/* =========================================================================
   Backpacker Buddy — data
   Typical one-way fares in USD, based on budget-carrier sale/normal pricing.
   These are planning estimates; the deep links show live prices.
   ========================================================================= */

const REGIONS = [
  {
    id: "california",
    name: "California, USA",
    cities: [
      { code: "LAX", name: "Los Angeles" },
      { code: "SFO", name: "San Francisco" },
      { code: "SAN", name: "San Diego" },
      { code: "SJC", name: "San Jose" },
      { code: "OAK", name: "Oakland" },
      { code: "SMF", name: "Sacramento" },
    ],
  },
  {
    id: "australia",
    name: "Australia",
    cities: [
      { code: "SYD", name: "Sydney" },
      { code: "MEL", name: "Melbourne" },
      { code: "BNE", name: "Brisbane" },
      { code: "PER", name: "Perth" },
      { code: "OOL", name: "Gold Coast" },
      { code: "CNS", name: "Cairns" },
      { code: "ADL", name: "Adelaide" },
      { code: "DRW", name: "Darwin" },
    ],
  },
  {
    id: "sea",
    name: "Southeast Asia",
    cities: [
      { code: "BKK", name: "Bangkok, Thailand" },
      { code: "CNX", name: "Chiang Mai, Thailand" },
      { code: "HKT", name: "Phuket, Thailand" },
      { code: "KBV", name: "Krabi, Thailand" },
      { code: "SGN", name: "Ho Chi Minh City, Vietnam" },
      { code: "HAN", name: "Hanoi, Vietnam" },
      { code: "DAD", name: "Da Nang, Vietnam" },
      { code: "DPS", name: "Bali (Denpasar), Indonesia" },
      { code: "CGK", name: "Jakarta, Indonesia" },
      { code: "KUL", name: "Kuala Lumpur, Malaysia" },
      { code: "PEN", name: "Penang, Malaysia" },
      { code: "SIN", name: "Singapore" },
      { code: "MNL", name: "Manila, Philippines" },
      { code: "CEB", name: "Cebu, Philippines" },
      { code: "PNH", name: "Phnom Penh, Cambodia" },
      { code: "REP", name: "Siem Reap, Cambodia" },
      { code: "VTE", name: "Vientiane, Laos" },
      { code: "LPQ", name: "Luang Prabang, Laos" },
    ],
  },
];

/* Highlighted city-pair deals. low = great sale fare, typ = normal low-season
   range. Symmetric: a search in either direction matches. */
const FLIGHT_DEALS = [
  // ---- California <-> Australia ----
  { pair: ["LAX", "SYD"], low: 400, typ: [550, 750],
    airlines: "Jetstar (seasonal nonstop), Fiji Airways via Nadi, Qantas/Delta/United sale fares",
    note: "Jetstar flash sales dip to ~$349 one-way. Fiji Airways via Nadi is reliably the cheapest full-service option and the stopover in Fiji is free." },
  { pair: ["LAX", "MEL"], low: 420, typ: [600, 800],
    airlines: "Qantas, United, Fiji Airways via Nadi, Air Canada via Vancouver",
    note: "Watch Qantas' 2–3 sales per year; Melbourne fares often match Sydney's within days of a sale starting." },
  { pair: ["SFO", "SYD"], low: 450, typ: [600, 850],
    airlines: "United (nonstop), Fiji Airways via Nadi, Qantas",
    note: "If LAX is >$100 cheaper, a $49 LAX positioning flight usually still wins." },
  { pair: ["LAX", "BNE"], low: 450, typ: [600, 800],
    airlines: "Qantas (nonstop), Air New Zealand via Auckland",
    note: "Brisbane is a great east-coast entry point — start north, work south with the seasons." },

  // ---- Australia <-> Southeast Asia ----
  { pair: ["PER", "DPS"], low: 60, typ: [90, 150],
    airlines: "Jetstar, Batik Air, AirAsia Indonesia",
    note: "Australia's cheapest back door to Asia — 3.5 hours, sale fares regularly under AUD 99." },
  { pair: ["DRW", "DPS"], low: 99, typ: [130, 190],
    airlines: "Jetstar",
    note: "Shortest hop from Australia to Bali (2.5h). Handy if you're ending a lap of the Top End." },
  { pair: ["SYD", "DPS"], low: 150, typ: [210, 300],
    airlines: "Jetstar (nonstop), Batik Air via KUL",
    note: "Jetstar Friday Frenzy regularly has SYD–Bali around AUD 199." },
  { pair: ["MEL", "DPS"], low: 140, typ: [200, 280],
    airlines: "Jetstar, Batik Air",
    note: "Book the 'Starter' fare and pack carry-on only — checked bags add ~$40 each way." },
  { pair: ["BNE", "DPS"], low: 150, typ: [210, 300],
    airlines: "Jetstar, Virgin Australia",
    note: "Virgin's sales here are competitive with Jetstar — compare both." },
  { pair: ["SYD", "KUL"], low: 160, typ: [230, 320],
    airlines: "AirAsia X, Batik Air, Malaysia Airlines",
    note: "KUL is AirAsia's mega-hub — landing here makes every onward SEA flight cheap." },
  { pair: ["SYD", "BKK"], low: 200, typ: [280, 380],
    airlines: "Thai Airways sales, AirAsia X via KUL, Jetstar via DPS",
    note: "Nonstops are pricier; self-connecting via Bali or KUL on sale fares can halve it." },
  { pair: ["MEL", "SGN"], low: 150, typ: [220, 320],
    airlines: "VietJet (nonstop), Vietnam Airlines",
    note: "VietJet's Melbourne–Saigon launch fares are some of the best AU–Asia value going." },
  { pair: ["SYD", "SGN"], low: 180, typ: [250, 350],
    airlines: "VietJet, Vietnam Airlines",
    note: "Vietnam makes a cheap first stop — then overland north or fly on for pocket change." },

  // ---- within Southeast Asia ----
  { pair: ["KUL", "BKK"], low: 25, typ: [35, 60],
    airlines: "AirAsia (to Don Mueang/DMK), Batik Air",
    note: "One of the cheapest international flights on Earth. AirAsia lands at DMK, not BKK." },
  { pair: ["KUL", "SIN"], low: 15, typ: [25, 45],
    airlines: "AirAsia, Scoot, Batik Air",
    note: "Also consider the bus (~$12, 5h) — city centre to city centre." },
  { pair: ["KUL", "DPS"], low: 35, typ: [50, 80],
    airlines: "AirAsia, Batik Air",
    note: "AirAsia BIG sales drop this under $30 several times a year." },
  { pair: ["SIN", "DPS"], low: 45, typ: [60, 95],
    airlines: "Scoot, Jetstar, AirAsia",
    note: "Scoot flash sales are frequent; Tuesday releases." },
  { pair: ["SIN", "BKK"], low: 40, typ: [55, 85],
    airlines: "Scoot, AirAsia via KUL",
    note: "Scoot to DMK is usually cheapest." },
  { pair: ["BKK", "SGN"], low: 35, typ: [50, 80],
    airlines: "VietJet, Thai AirAsia",
    note: "80-minute hop; VietJet sale fares from ~$25 + bag fees." },
  { pair: ["BKK", "HAN"], low: 40, typ: [55, 85],
    airlines: "VietJet, Thai AirAsia",
    note: "Fly into Hanoi, travel south through Vietnam, exit from Saigon — no backtracking." },
  { pair: ["SGN", "HAN"], low: 25, typ: [40, 65],
    airlines: "VietJet, Bamboo Airways, Vietnam Airlines",
    note: "Or take the Reunification Express sleeper train (~$45) and see the whole coast." },
  { pair: ["SGN", "DAD"], low: 20, typ: [30, 55],
    airlines: "VietJet, Bamboo Airways",
    note: "Da Nang is the gateway to Hoi An (45 min by bus)." },
  { pair: ["BKK", "CNX"], low: 15, typ: [25, 45],
    airlines: "Thai AirAsia, Nok Air, Thai Lion Air",
    note: "Or the excellent overnight sleeper train (~$25–35, book 2nd class lower berth)." },
  { pair: ["BKK", "HKT"], low: 18, typ: [30, 55],
    airlines: "Thai AirAsia, Nok Air, Thai Lion Air",
    note: "Flights beat the 12-hour bus for almost the same price." },
  { pair: ["BKK", "REP"], low: 45, typ: [60, 95],
    airlines: "Thai AirAsia, Bangkok Airways",
    note: "Short but overpriced route — the direct bus is $25–35 (8h) if you're patient." },
  { pair: ["BKK", "PNH"], low: 45, typ: [60, 90],
    airlines: "Thai AirAsia",
    note: "Consider Bangkok → Siem Reap (Angkor) overland, then bus to Phnom Penh ($10)." },
  { pair: ["SGN", "PNH"], low: 60, typ: [75, 110],
    airlines: "Cambodia Angkor Air, VietJet",
    note: "The Giant Ibis bus is $18–25 (6.5h) and often the smarter choice." },
  { pair: ["SGN", "DPS"], low: 70, typ: [90, 130],
    airlines: "VietJet (nonstop)",
    note: "VietJet's nonstop makes Vietnam → Bali cheap; otherwise connect via KUL for less." },
  { pair: ["HAN", "VTE"], low: 80, typ: [100, 150],
    airlines: "Lao Airlines, Vietnam Airlines",
    note: "Laos flights are pricey for the distance — the Hanoi→Vientiane sleeper bus is ~$25." },
  { pair: ["HAN", "LPQ"], low: 90, typ: [110, 160],
    airlines: "Lao Airlines",
    note: "Or go overland to Vientiane and ride the new Laos–China Railway north (~$8–15)." },
  { pair: ["MNL", "CEB"], low: 20, typ: [30, 55],
    airlines: "Cebu Pacific, Philippines AirAsia",
    note: "Cebu Pacific Piso sales drop domestic fares to almost nothing — set an alert." },
  { pair: ["BKK", "MNL"], low: 60, typ: [85, 130],
    airlines: "Cebu Pacific, Philippines AirAsia",
    note: "The Philippines is a detour from the mainland circuit — bundle it with Cebu/Palawan." },
  { pair: ["DPS", "CGK"], low: 30, typ: [40, 65],
    airlines: "Lion Air, Citilink, AirAsia Indonesia",
    note: "Domestic Indonesia is dirt cheap — Java, Lombok and Flores are all short hops." },
];

/* Corridor-level fallback when the exact pair isn't in FLIGHT_DEALS. */
const CORRIDORS = {
  "california-australia": {
    label: "California ↔ Australia",
    typ: [500, 900],
    advice: "Cheapest months: April–May and August–September (Australian shoulder seasons). Track Jetstar's transpacific sales and Qantas' 2–3 annual sales; Fiji Airways via Nadi is consistently the budget pick. Book 2–5 months out. If Southeast Asia is on your route anyway, price California → Bangkok/Kuala Lumpur too — flying the Pacific into Asia first is often $100–200 cheaper, and the Australia hop from Bali is tiny.",
  },
  "california-sea": {
    label: "California ↔ Southeast Asia",
    typ: [350, 700],
    advice: "Sale fares on EVA Air, China Airlines and Korean Air via their hubs regularly hit $350–450 one-way to Bangkok. ZipAir (LAX/SFO–Tokyo) plus an AirAsia hop is the DIY budget combo. Taipei, Seoul and Tokyo self-connections open free stopovers.",
  },
  "australia-sea": {
    label: "Australia ↔ Southeast Asia",
    typ: [150, 350],
    advice: "Perth and Darwin are Australia's cheap back doors to Asia. Jetstar, AirAsia X, VietJet and Batik Air run monthly sales — Friday afternoons (AEST) for Jetstar's Friday Frenzy. Bali and Kuala Lumpur are the two cheapest entry points; everything in SEA is a $30–80 hop from KUL.",
  },
  "sea-sea": {
    label: "Within Southeast Asia",
    typ: [25, 90],
    advice: "AirAsia, VietJet, Scoot, Cebu Pacific and Lion Air keep intra-SEA fares tiny — but bag fees can double a $30 fare, so pack carry-on. For trips under ~500 km, buses and trains (book on 12Go) are often cheaper, comfier and station-to-station.",
  },
  "california-california": { label: "Within California", typ: [40, 120],
    advice: "Southwest, Alaska and United shuttle routes — or just drive." },
  "australia-australia": { label: "Within Australia", typ: [60, 180],
    advice: "Jetstar and Virgin sales; east-coast Greyhound hop-on-hop-off passes suit backpackers." },
};

/* Accommodation intel. Prices = USD/night typical. */
const STAYS = {
  "Bangkok": { country: "Thailand", dorm: [8, 15], private: [18, 30], hotel: [25, 45],
    areas: "Ari or Phaya Thai for local vibes on the BTS line; Old City (Banglamphu) for sights; skip the Khao San party blocks if you value sleep.",
    tip: "Bangkok hostels are some of the world's best-value — 8.5+ rated places with pools exist under $12." },
  "Chiang Mai": { country: "Thailand", dorm: [6, 12], private: [14, 25], hotel: [20, 38],
    areas: "Old City for walkability, Nimman for cafés and digital-nomad comforts.",
    tip: "Monthly guesthouse rates drop to $200–300 if you linger — ask in person." },
  "Phuket": { country: "Thailand", dorm: [8, 16], private: [20, 35], hotel: [28, 55],
    areas: "Phuket Old Town for charm and cheap eats; Kata/Karon quieter than Patong.",
    tip: "Stay in Old Town and day-trip to beaches by songthaew ($1) — beachfront prices double everything." },
  "Krabi": { country: "Thailand", dorm: [7, 14], private: [16, 28], hotel: [22, 45],
    areas: "Ao Nang for beach access, Krabi Town for half the price.",
    tip: "Railay's cheap-ish bungalows book out — reserve those 2+ weeks ahead." },
  "Hanoi": { country: "Vietnam", dorm: [5, 10], private: [14, 25], hotel: [20, 35],
    areas: "Old Quarter for the classic chaos, Tay Ho (West Lake) for calm.",
    tip: "Hostel 'free beer hour' places are party spots — check reviews for 'quiet' if that's not your scene." },
  "Ho Chi Minh City": { country: "Vietnam", dorm: [6, 11], private: [15, 26], hotel: [22, 40],
    areas: "District 1 (around Bui Vien is loud; go 3–4 blocks out), District 3 for local flavour.",
    tip: "$20 gets a genuinely nice private room here — Vietnam is where hotel upgrades cost least." },
  "Da Nang": { country: "Vietnam", dorm: [5, 10], private: [13, 24], hotel: [18, 35],
    areas: "My Khe beach side for sea air; An Thuong for the traveller enclave.",
    tip: "Consider staying in Hoi An instead (30 min) — homestays there are $15–25 and gorgeous." },
  "Siem Reap": { country: "Cambodia", dorm: [4, 9], private: [12, 22], hotel: [18, 35],
    areas: "Wat Bo Road area — close to the centre, quieter than Pub Street.",
    tip: "Hostels with pools under $8 are normal here. Get one — Angkor days are hot." },
  "Phnom Penh": { country: "Cambodia", dorm: [5, 10], private: [13, 24], hotel: [20, 38],
    areas: "BKK1 for comfort, Riverside for location.",
    tip: "Standards vary more than elsewhere — filter 8.0+ with 200+ reviews." },
  "Luang Prabang": { country: "Laos", dorm: [5, 10], private: [14, 25], hotel: [20, 40],
    areas: "Old Town peninsula — everything is walkable.",
    tip: "Guesthouses run by families often beat hostels on both price and cleanliness here." },
  "Vientiane": { country: "Laos", dorm: [5, 10], private: [13, 24], hotel: [18, 35],
    areas: "Near Nam Phou fountain for the compact centre.",
    tip: "Most travellers only need a night or two — it's a transit stop, spend your Laos time in Luang Prabang / Vang Vieng." },
  "Kuala Lumpur": { country: "Malaysia", dorm: [7, 13], private: [18, 30], hotel: [25, 45],
    areas: "Chinatown (Petaling Street) for hostels and food; Bukit Bintang for city buzz.",
    tip: "KL has luxury-grade capsule hostels at $12–15 — great for a comfy reset between flights." },
  "Penang": { country: "Malaysia", dorm: [6, 12], private: [15, 28], hotel: [22, 40],
    areas: "George Town heritage core — street art, hawker food, everything walkable.",
    tip: "Heritage shophouse guesthouses are the move — character for hostel prices." },
  "Singapore": { country: "Singapore", dorm: [20, 35], private: [60, 100], hotel: [80, 140],
    areas: "Chinatown and Lavender for the (relatively) affordable beds.",
    tip: "The budget-killer of SEA. Capsule pods keep it sane; 2–3 nights is plenty." },
  "Bali (Canggu)": { country: "Indonesia", dorm: [7, 14], private: [18, 35], hotel: [25, 50],
    areas: "Canggu for surf/social, Ubud for jungle calm, Uluwatu for cliffs and waves.",
    tip: "Guesthouses ('homestays') at $15–20 with breakfast often beat hostels. Monthly villa-room deals abound." },
  "Ubud": { country: "Indonesia", dorm: [6, 12], private: [15, 30], hotel: [22, 45],
    areas: "Just off Monkey Forest Road, or Penestanan for rice-field quiet.",
    tip: "Family compounds rent beautiful rooms with breakfast for $15 — book 1 night online, extend in person for less." },
  "Jakarta": { country: "Indonesia", dorm: [6, 12], private: [15, 28], hotel: [22, 40],
    areas: "Around Cikini/Menteng — most travellers just transit here.",
    tip: "Honestly? Fly into Bali or Yogyakarta instead unless you have business here." },
  "Manila": { country: "Philippines", dorm: [7, 13], private: [18, 32], hotel: [25, 45],
    areas: "Makati (Poblacion) — safe, walkable, great food scene.",
    tip: "Most backpackers transit fast to the islands — Poblacion is the one neighbourhood worth a night." },
  "Cebu": { country: "Philippines", dorm: [6, 12], private: [16, 30], hotel: [22, 42],
    areas: "Cebu City for transit; Moalboal (3h south) is the real draw.",
    tip: "Island-hopping beds (Moalboal, Siquijor, Bohol) are $8–15 — book only 1–2 days ahead, stay flexible." },
  "Sydney": { country: "Australia", dorm: [25, 45], private: [70, 110], hotel: [90, 150],
    areas: "Newtown for character, Coogee/Bondi for beach hostels, CBD YHA for location.",
    tip: "Weekly hostel rates cut 15–25%. If working-holidaying, many hostels trade beds for a few hours' work." },
  "Melbourne": { country: "Australia", dorm: [22, 40], private: [65, 100], hotel: [85, 140],
    areas: "Fitzroy/Collingwood for the cool stuff, CBD for transit ease.",
    tip: "Melbourne hostels are slightly cheaper than Sydney's and the free city tram zone saves real money." },
  "Brisbane": { country: "Australia", dorm: [20, 38], private: [60, 95], hotel: [80, 130],
    areas: "South Bank / West End.",
    tip: "Cheaper than Sydney/Melbourne — a good place to sort logistics before heading up the coast." },
  "Cairns": { country: "Australia", dorm: [20, 36], private: [55, 90], hotel: [75, 125],
    areas: "City centre near the Esplanade lagoon.",
    tip: "Book reef trips through your hostel — the discounts are genuine here." },
  "Gold Coast": { country: "Australia", dorm: [22, 40], private: [60, 100], hotel: [85, 140],
    areas: "Surfers Paradise for the action, Burleigh Heads for the better beach vibe.",
    tip: "Hostels here compete hard — look for free surfboard hire." },
  "Perth": { country: "Australia", dorm: [22, 38], private: [60, 95], hotel: [80, 130],
    areas: "Northbridge — hostels, food, nightlife in one walkable pocket.",
    tip: "Your last cheap-flight gateway to Asia — many backpackers end the Australia leg here on purpose." },
};

/* Daily on-the-ground budgets (food + local transport + activities + stay), USD. */
const DAILY_BUDGET = {
  shoestring: { sea: 35, australia: 75, label: "Shoestring (dorms, street food, buses)" },
  flashpacker: { sea: 55, australia: 110, label: "Flashpacker (privates, some tours & flights)" },
};

/* Route strategies. Legs reference typical low fares from FLIGHT_DEALS. */
const ROUTE_STRATEGIES = [
  {
    id: "reverse-loop",
    name: "The Reverse Loop",
    emoji: "🔄",
    tagline: "Usually the cheapest — fly into Asia first, save Australia for last.",
    auShare: 0.35,
    legs: [
      { from: "California", to: "Bangkok", mode: "flight", est: 420, note: "EVA/China Airlines/Korean sale fare, or ZipAir via Tokyo. Cheapest transpacific corridor." },
      { from: "Bangkok", to: "Chiang Mai & N. Thailand", mode: "ground", est: 30, note: "Sleeper train up, slow-boat or bus into Laos if you like." },
      { from: "Chiang Mai", to: "Hanoi", mode: "flight", est: 70, note: "Or overland through Laos (Luang Prabang) — slower, unforgettable." },
      { from: "Hanoi", to: "Ho Chi Minh City", mode: "ground", est: 45, note: "3–4 weeks down the coast: Ha Long, Hoi An, Da Lat. Sleeper trains/buses." },
      { from: "Ho Chi Minh City", to: "Bali", mode: "flight", est: 90, note: "VietJet nonstop, or via KUL for less." },
      { from: "Bali", to: "Sydney / Melbourne", mode: "flight", est: 170, note: "Jetstar sale fare. The cheap way into Australia." },
      { from: "Australia east coast", to: "", mode: "ground", est: 150, note: "Greyhound pass or a shared campervan relocation deal." },
      { from: "Sydney", to: "California", mode: "flight", est: 500, note: "Jetstar/Fiji Airways home. Book once you know your dates." },
    ],
    why: "You hit the expensive country (Australia) last, when you know exactly what's left in the kitty. Transpacific fares into Bangkok run $100–200 under Sydney fares, and your Australia entry becomes a ~$170 Bali hop instead of a $600 ocean crossing.",
  },
  {
    id: "classic-southbound",
    name: "The Classic Southbound",
    emoji: "🇦🇺",
    tagline: "Australia first while your budget is fresh, then get cheap in Asia.",
    auShare: 0.4,
    legs: [
      { from: "California", to: "Sydney", mode: "flight", est: 450, note: "Jetstar/Fiji Airways sale fare. April–May and Aug–Sep are cheapest." },
      { from: "Sydney", to: "Cairns (east coast)", mode: "ground", est: 180, note: "The classic backpacker run: Byron, Gold Coast, Noosa, Whitsundays." },
      { from: "Cairns/Brisbane", to: "Bali", mode: "flight", est: 180, note: "Or reposition to Darwin — DRW–Bali from $99." },
      { from: "Bali", to: "Kuala Lumpur", mode: "flight", est: 50, note: "AirAsia. KUL unlocks cheap fares to everywhere in SEA." },
      { from: "Kuala Lumpur", to: "Bangkok", mode: "flight", est: 40, note: "Or train up through Penang — one of Asia's great rail rides." },
      { from: "Thailand", to: "Vietnam (overland loop)", mode: "ground", est: 120, note: "Thailand → Cambodia (Angkor) → Vietnam by bus; visas on the way." },
      { from: "Ho Chi Minh City", to: "California", mode: "flight", est: 550, note: "One-way home; EVA/Korean via their hubs price best." },
    ],
    why: "Do the physically big, expensive country while you're fresh and funded, then let ultra-cheap Asia stretch the tail of your trip. Every flight after Australia costs less than a night out in Sydney.",
  },
  {
    id: "perth-backdoor",
    name: "The Perth Back Door",
    emoji: "🚪",
    tagline: "Use Australia's west coast as the world's cheapest exit to Asia.",
    auShare: 0.4,
    legs: [
      { from: "California", to: "Sydney", mode: "flight", est: 450, note: "Sale fare in; do the east coast first." },
      { from: "East coast", to: "Melbourne", mode: "ground", est: 100, note: "Buses/rideshares down the coast." },
      { from: "Melbourne", to: "Perth", mode: "flight", est: 120, note: "Jetstar/Virgin domestic sale. Margaret River side-trip if time allows." },
      { from: "Perth", to: "Bali", mode: "flight", est: 90, note: "The famous cheap hop — under AUD 99 in sales, 3.5 hours." },
      { from: "Bali", to: "Kuala Lumpur", mode: "flight", est: 50, note: "AirAsia into the hub." },
      { from: "Kuala Lumpur", to: "Bangkok + mainland loop", mode: "flight", est: 40, note: "Thailand → Laos → Vietnam overland from here." },
      { from: "Bangkok", to: "California", mode: "flight", est: 480, note: "Fly home from the region's best-connected hub." },
    ],
    why: "Perth–Bali is Australia's cheapest international flight, which turns the expensive 'Australia → Asia' leg into pocket change. You also see the west coast most backpackers skip.",
  },
];

const DEAL_HACKS = [
  { icon: "📅", title: "Know the sale calendar",
    body: "Jetstar Friday Frenzy: Friday ~4pm AEST weekly. AirAsia BIG Sale: ~4× a year (Feb/Mar, May/Jun, Aug/Sep, Nov). Scoot flash sales: most Tuesdays. Cebu Pacific Piso sales: around Philippine holidays. VietJet: sales nearly monthly. Set calendar reminders — sale fares are 40–70% off." },
  { icon: "🎒", title: "Carry-on only changes the math",
    body: "Budget-carrier bag fees ($25–45 per flight) can double a $40 fare across a multi-hop trip. A 35–40L pack under 7kg flies free on AirAsia, VietJet, Scoot and Jetstar. Ten flights ≈ $350 saved." },
  { icon: "🔔", title: "Track, don't stalk",
    body: "Set Google Flights price tracking on your long-haul legs 3–5 months out and book when a genuine dip shows. For CA↔Australia, under $500 one-way is 'book it now' territory; under $420 is exceptional." },
  { icon: "🚌", title: "Under 500 km, go by land",
    body: "Buses and trains in SEA are comfortable, cheap and station-to-station: Bangkok–Chiang Mai sleeper $25, Saigon–Phnom Penh bus $20, KL–Singapore bus $12. Book on 12Go. You save a night's accommodation on sleepers, too." },
  { icon: "🏨", title: "The clean-bed formula",
    body: "Filter stays to rating ≥ 8.3 with 150+ reviews, then read only the recent negative reviews — that's where cleanliness truth lives. On Hostelworld sort by rating, not price: in SEA the difference between a 7.8 and a 9.2 hostel is often $2." },
  { icon: "↩️", title: "Book flexible, especially early legs",
    body: "Choose free-cancellation stays (Booking/Agoda make this a filter) for your first nights in each country and lock in the rest once you're on the ground. Plans made from home rarely survive week two." },
  { icon: "💳", title: "Kill the hidden 3–7%",
    body: "Use a no-foreign-fee card (Wise/Revolut/Charles Schwab), always pay in local currency (decline 'dynamic currency conversion'), and skip airport exchange counters. In Vietnam and Indonesia, withdraw large amounts less often — ATM fees are per-transaction." },
  { icon: "🗓️", title: "Fly on the cheap days",
    body: "Tuesday/Wednesday departures price lowest on long-haul; intra-SEA barely varies. Avoid arriving anywhere during Lunar New Year, Songkran (mid-April) or Christmas–NYE unless you've booked well ahead." },
  { icon: "🛂", title: "Budget the visas",
    body: "Thailand: 60 days free (US passport). Indonesia: $35 visa on arrival. Vietnam: e-visa $25 (apply 1–2 weeks early). Cambodia: $30 e-visa. Laos: ~$40 on arrival. Australia: free ETA (or the Work & Holiday visa if you want to earn AUD along the way)." },
  { icon: "🧭", title: "Season your route",
    body: "SEA mainland is driest Nov–Apr; Bali is best Apr–Oct; Australia's east coast shines Sep–Nov and Mar–May. The Reverse Loop timed to leave California in October threads all three." },
];
