/* =========================================================================
   Backpacker Buddy — data
   Typical one-way fares in USD, based on budget-carrier sale/normal pricing.
   These are planning estimates; the deep links show live prices.
   ========================================================================= */

const REGIONS = [
  {
    id: "california",
    name: "California, USA",
    cities: [
      { code: "LAX", name: "Los Angeles" },
      { code: "SFO", name: "San Francisco" },
      { code: "SAN", name: "San Diego" },
      { code: "SJC", name: "San Jose" },
      { code: "OAK", name: "Oakland" },
      { code: "SMF", name: "Sacramento" },
    ],
  },
  {
    id: "australia",
    name: "Australia",
    cities: [
      { code: "SYD", name: "Sydney" },
      { code: "MEL", name: "Melbourne" },
      { code: "BNE", name: "Brisbane" },
      { code: "PER", name: "Perth" },
      { code: "OOL", name: "Gold Coast" },
      { code: "CNS", name: "Cairns" },
      { code: "ADL", name: "Adelaide" },
      { code: "DRW", name: "Darwin" },
    ],
  },
  {
    id: "sea",
    name: "Southeast Asia",
    cities: [
      { code: "BKK", name: "Bangkok, Thailand" },
      { code: "CNX", name: "Chiang Mai, Thailand" },
      { code: "HKT", name: "Phuket, Thailand" },
      { code: "KBV", name: "Krabi, Thailand" },
      { code: "SGN", name: "Ho Chi Minh City, Vietnam" },
      { code: "HAN", name: "Hanoi, Vietnam" },
      { code: "DAD", name: "Da Nang, Vietnam" },
      { code: "DPS", name: "Bali (Denpasar), Indonesia" },
      { code: "CGK", name: "Jakarta, Indonesia" },
      { code: "KUL", name: "Kuala Lumpur, Malaysia" },
      { code: "PEN", name: "Penang, Malaysia" },
      { code: "SIN", name: "Singapore" },
      { code: "MNL", name: "Manila, Philippines" },
      { code: "CEB", name: "Cebu, Philippines" },
      { code: "PNH", name: "Phnom Penh, Cambodia" },
      { code: "REP", name: "Siem Reap, Cambodia" },
      { code: "VTE", name: "Vientiane, Laos" },
      { code: "LPQ", name: "Luang Prabang, Laos" },
    ],
  },
  {
    id: "latam",
    name: "Latin America",
    cities: [
      { code: "MEX", name: "Mexico City, Mexico" },
      { code: "CUN", name: "Cancún, Mexico" },
      { code: "OAX", name: "Oaxaca, Mexico" },
      { code: "GUA", name: "Guatemala City, Guatemala" },
      { code: "SJO", name: "San José, Costa Rica" },
      { code: "PTY", name: "Panama City, Panama" },
      { code: "MDE", name: "Medellín, Colombia" },
      { code: "BOG", name: "Bogotá, Colombia" },
      { code: "CTG", name: "Cartagena, Colombia" },
      { code: "UIO", name: "Quito, Ecuador" },
      { code: "LIM", name: "Lima, Peru" },
      { code: "CUZ", name: "Cusco, Peru" },
      { code: "LPB", name: "La Paz, Bolivia" },
      { code: "SCL", name: "Santiago, Chile" },
      { code: "EZE", name: "Buenos Aires, Argentina" },
      { code: "GIG", name: "Rio de Janeiro, Brazil" },
    ],
  },
  {
    id: "europe",
    name: "Europe",
    cities: [
      { code: "LIS", name: "Lisbon, Portugal" },
      { code: "MAD", name: "Madrid, Spain" },
      { code: "BCN", name: "Barcelona, Spain" },
      { code: "LON", name: "London, UK" },
      { code: "PAR", name: "Paris, France" },
      { code: "AMS", name: "Amsterdam, Netherlands" },
      { code: "BER", name: "Berlin, Germany" },
      { code: "PRG", name: "Prague, Czechia" },
      { code: "BUD", name: "Budapest, Hungary" },
      { code: "KRK", name: "Kraków, Poland" },
      { code: "ATH", name: "Athens, Greece" },
      { code: "ROM", name: "Rome, Italy" },
      { code: "SPU", name: "Split, Croatia" },
      { code: "TIA", name: "Tirana, Albania" },
      { code: "BEG", name: "Belgrade, Serbia" },
      { code: "IST", name: "Istanbul, Türkiye" },
    ],
  },
  {
    id: "southasia",
    name: "South Asia",
    cities: [
      { code: "DEL", name: "Delhi, India" },
      { code: "BOM", name: "Mumbai, India" },
      { code: "JAI", name: "Jaipur, India" },
      { code: "GOI", name: "Goa, India" },
      { code: "COK", name: "Kochi, India" },
      { code: "KTM", name: "Kathmandu, Nepal" },
      { code: "PKR", name: "Pokhara, Nepal" },
      { code: "CMB", name: "Colombo, Sri Lanka" },
    ],
  },
  {
    id: "eastasia",
    name: "East Asia",
    cities: [
      { code: "TYO", name: "Tokyo, Japan" },
      { code: "OSA", name: "Osaka, Japan" },
      { code: "SEL", name: "Seoul, South Korea" },
      { code: "TPE", name: "Taipei, Taiwan" },
      { code: "HKG", name: "Hong Kong" },
      { code: "SHA", name: "Shanghai, China" },
    ],
  },
  {
    id: "restofworld",
    name: "More of the world",
    cities: [
      { code: "NYC", name: "New York, USA" },
      { code: "SEA", name: "Seattle, USA" },
      { code: "YVR", name: "Vancouver, Canada" },
      { code: "AKL", name: "Auckland, New Zealand" },
      { code: "ZQN", name: "Queenstown, New Zealand" },
      { code: "NAN", name: "Nadi, Fiji" },
      { code: "DXB", name: "Dubai, UAE" },
      { code: "AMM", name: "Amman, Jordan" },
      { code: "CAI", name: "Cairo, Egypt" },
      { code: "RAK", name: "Marrakech, Morocco" },
      { code: "NBO", name: "Nairobi, Kenya" },
      { code: "CPT", name: "Cape Town, South Africa" },
    ],
  },
];

/* Budget-airline & money intel per region — shown when a route touches it. */
const REGION_TIPS = {
  california: "From California, the cheap long-haul tricks: position through LAX (most competition), watch ZipAir (Tokyo), French Bee (Paris), Norse (Europe), Volaris/Viva (Mexico — or walk across at the CBX Tijuana bridge for half-price Latin America fares).",
  australia: "Australia's budget carriers: Jetstar and Virgin Australia domestically; Jetstar, AirAsia X, VietJet and Batik Air internationally. Perth and Darwin are the cheap back doors to Asia.",
  sea: "Southeast Asia runs on AirAsia, VietJet, Scoot, Cebu Pacific and Lion Air — fares are tiny but bag fees aren't, so pack carry-on. Under ~500 km, buses and trains (book on 12Go) usually win.",
  latam: "Latin America's budget carriers: Volaris and VivaAerobus (Mexico), Wingo and JetSmart (Colombia/Chile/Peru), Azul and GOL (Brazil), Arajet (Caribbean hops). Long-distance overnight buses are excellent and often nicer than flying — 'cama' class seats recline flat.",
  europe: "Europe is the budget-flight motherland: Ryanair, Wizz Air, easyJet, Vueling and Transavia sell $15–60 hops — but check bag rules and airport locations (some 'city' airports are an hour out). FlixBus and rail passes cover the gaps.",
  southasia: "India and around: IndiGo, Air India Express and SpiceJet keep domestic fares $25–60. Trains are the real network — book Indian Railways early via 12Go or IRCTC; sleeper class is the backpacker classic.",
  eastasia: "East Asia's budget players: Peach and ZipAir (Japan), Jeju Air and T'way (Korea), Scoot and AirAsia connect it all to SEA. Rail passes (JR Pass, KTX) beat flying domestically once you're there.",
  restofworld: "No curated intel for this region yet — lean on the live links, book 4–8 weeks out, fly Tuesday/Wednesday, and check which low-cost carriers serve the airport (Wikipedia's airport pages list every route and airline).",
};

/* Highlighted city-pair deals. low = great sale fare, typ = normal low-season
   range. Symmetric: a search in either direction matches. */
const FLIGHT_DEALS = [
  // ---- California <-> Australia ----
  { pair: ["LAX", "SYD"], low: 400, typ: [550, 750],
    airlines: "Jetstar (seasonal nonstop), Fiji Airways via Nadi, Qantas/Delta/United sale fares",
    note: "Jetstar flash sales dip to ~$349 one-way. Fiji Airways via Nadi is reliably the cheapest full-service option and the stopover in Fiji is free." },
  { pair: ["LAX", "MEL"], low: 420, typ: [600, 800],
    airlines: "Qantas, United, Fiji Airways via Nadi, Air Canada via Vancouver",
    note: "Watch Qantas' 2–3 sales per year; Melbourne fares often match Sydney's within days of a sale starting." },
  { pair: ["SFO", "SYD"], low: 450, typ: [600, 850],
    airlines: "United (nonstop), Fiji Airways via Nadi, Qantas",
    note: "If LAX is >$100 cheaper, a $49 LAX positioning flight usually still wins." },
  { pair: ["LAX", "BNE"], low: 450, typ: [600, 800],
    airlines: "Qantas (nonstop), Air New Zealand via Auckland",
    note: "Brisbane is a great east-coast entry point — start north, work south with the seasons." },

  // ---- Australia <-> Southeast Asia ----
  { pair: ["PER", "DPS"], low: 60, typ: [90, 150],
    airlines: "Jetstar, Batik Air, AirAsia Indonesia",
    note: "Australia's cheapest back door to Asia — 3.5 hours, sale fares regularly under AUD 99." },
  { pair: ["DRW", "DPS"], low: 99, typ: [130, 190],
    airlines: "Jetstar",
    note: "Shortest hop from Australia to Bali (2.5h). Handy if you're ending a lap of the Top End." },
  { pair: ["SYD", "DPS"], low: 150, typ: [210, 300],
    airlines: "Jetstar (nonstop), Batik Air via KUL",
    note: "Jetstar Friday Frenzy regularly has SYD–Bali around AUD 199." },
  { pair: ["MEL", "DPS"], low: 140, typ: [200, 280],
    airlines: "Jetstar, Batik Air",
    note: "Book the 'Starter' fare and pack carry-on only — checked bags add ~$40 each way." },
  { pair: ["BNE", "DPS"], low: 150, typ: [210, 300],
    airlines: "Jetstar, Virgin Australia",
    note: "Virgin's sales here are competitive with Jetstar — compare both." },
  { pair: ["SYD", "KUL"], low: 160, typ: [230, 320],
    airlines: "AirAsia X, Batik Air, Malaysia Airlines",
    note: "KUL is AirAsia's mega-hub — landing here makes every onward SEA flight cheap." },
  { pair: ["SYD", "BKK"], low: 200, typ: [280, 380],
    airlines: "Thai Airways sales, AirAsia X via KUL, Jetstar via DPS",
    note: "Nonstops are pricier; self-connecting via Bali or KUL on sale fares can halve it." },
  { pair: ["MEL", "SGN"], low: 150, typ: [220, 320],
    airlines: "VietJet (nonstop), Vietnam Airlines",
    note: "VietJet's Melbourne–Saigon launch fares are some of the best AU–Asia value going." },
  { pair: ["SYD", "SGN"], low: 180, typ: [250, 350],
    airlines: "VietJet, Vietnam Airlines",
    note: "Vietnam makes a cheap first stop — then overland north or fly on for pocket change." },

  // ---- within Southeast Asia ----
  { pair: ["KUL", "BKK"], low: 25, typ: [35, 60],
    airlines: "AirAsia (to Don Mueang/DMK), Batik Air",
    note: "One of the cheapest international flights on Earth. AirAsia lands at DMK, not BKK." },
  { pair: ["KUL", "SIN"], low: 15, typ: [25, 45],
    airlines: "AirAsia, Scoot, Batik Air",
    note: "Also consider the bus (~$12, 5h) — city centre to city centre." },
  { pair: ["KUL", "DPS"], low: 35, typ: [50, 80],
    airlines: "AirAsia, Batik Air",
    note: "AirAsia BIG sales drop this under $30 several times a year." },
  { pair: ["SIN", "DPS"], low: 45, typ: [60, 95],
    airlines: "Scoot, Jetstar, AirAsia",
    note: "Scoot flash sales are frequent; Tuesday releases." },
  { pair: ["SIN", "BKK"], low: 40, typ: [55, 85],
    airlines: "Scoot, AirAsia via KUL",
    note: "Scoot to DMK is usually cheapest." },
  { pair: ["BKK", "SGN"], low: 35, typ: [50, 80],
    airlines: "VietJet, Thai AirAsia",
    note: "80-minute hop; VietJet sale fares from ~$25 + bag fees." },
  { pair: ["BKK", "HAN"], low: 40, typ: [55, 85],
    airlines: "VietJet, Thai AirAsia",
    note: "Fly into Hanoi, travel south through Vietnam, exit from Saigon — no backtracking." },
  { pair: ["SGN", "HAN"], low: 25, typ: [40, 65],
    airlines: "VietJet, Bamboo Airways, Vietnam Airlines",
    note: "Or take the Reunification Express sleeper train (~$45) and see the whole coast." },
  { pair: ["SGN", "DAD"], low: 20, typ: [30, 55],
    airlines: "VietJet, Bamboo Airways",
    note: "Da Nang is the gateway to Hoi An (45 min by bus)." },
  { pair: ["BKK", "CNX"], low: 15, typ: [25, 45],
    airlines: "Thai AirAsia, Nok Air, Thai Lion Air",
    note: "Or the excellent overnight sleeper train (~$25–35, book 2nd class lower berth)." },
  { pair: ["BKK", "HKT"], low: 18, typ: [30, 55],
    airlines: "Thai AirAsia, Nok Air, Thai Lion Air",
    note: "Flights beat the 12-hour bus for almost the same price." },
  { pair: ["BKK", "REP"], low: 45, typ: [60, 95],
    airlines: "Thai AirAsia, Bangkok Airways",
    note: "Short but overpriced route — the direct bus is $25–35 (8h) if you're patient." },
  { pair: ["BKK", "PNH"], low: 45, typ: [60, 90],
    airlines: "Thai AirAsia",
    note: "Consider Bangkok → Siem Reap (Angkor) overland, then bus to Phnom Penh ($10)." },
  { pair: ["SGN", "PNH"], low: 60, typ: [75, 110],
    airlines: "Cambodia Angkor Air, VietJet",
    note: "The Giant Ibis bus is $18–25 (6.5h) and often the smarter choice." },
  { pair: ["SGN", "DPS"], low: 70, typ: [90, 130],
    airlines: "VietJet (nonstop)",
    note: "VietJet's nonstop makes Vietnam → Bali cheap; otherwise connect via KUL for less." },
  { pair: ["HAN", "VTE"], low: 80, typ: [100, 150],
    airlines: "Lao Airlines, Vietnam Airlines",
    note: "Laos flights are pricey for the distance — the Hanoi→Vientiane sleeper bus is ~$25." },
  { pair: ["HAN", "LPQ"], low: 90, typ: [110, 160],
    airlines: "Lao Airlines",
    note: "Or go overland to Vientiane and ride the new Laos–China Railway north (~$8–15)." },
  { pair: ["MNL", "CEB"], low: 20, typ: [30, 55],
    airlines: "Cebu Pacific, Philippines AirAsia",
    note: "Cebu Pacific Piso sales drop domestic fares to almost nothing — set an alert." },
  { pair: ["BKK", "MNL"], low: 60, typ: [85, 130],
    airlines: "Cebu Pacific, Philippines AirAsia",
    note: "The Philippines is a detour from the mainland circuit — bundle it with Cebu/Palawan." },
  { pair: ["DPS", "CGK"], low: 30, typ: [40, 65],
    airlines: "Lion Air, Citilink, AirAsia Indonesia",
    note: "Domestic Indonesia is dirt cheap — Java, Lombok and Flores are all short hops." },
];

/* Corridor-level fallback when the exact pair isn't in FLIGHT_DEALS. */
const CORRIDORS = {
  "california-australia": {
    label: "California ↔ Australia",
    typ: [500, 900],
    advice: "Cheapest months: April–May and August–September (Australian shoulder seasons). Track Jetstar's transpacific sales and Qantas' 2–3 annual sales; Fiji Airways via Nadi is consistently the budget pick. Book 2–5 months out. If Southeast Asia is on your route anyway, price California → Bangkok/Kuala Lumpur too — flying the Pacific into Asia first is often $100–200 cheaper, and the Australia hop from Bali is tiny.",
  },
  "california-sea": {
    label: "California ↔ Southeast Asia",
    typ: [350, 700],
    advice: "Sale fares on EVA Air, China Airlines and Korean Air via their hubs regularly hit $350–450 one-way to Bangkok. ZipAir (LAX/SFO–Tokyo) plus an AirAsia hop is the DIY budget combo. Taipei, Seoul and Tokyo self-connections open free stopovers.",
  },
  "australia-sea": {
    label: "Australia ↔ Southeast Asia",
    typ: [150, 350],
    advice: "Perth and Darwin are Australia's cheap back doors to Asia. Jetstar, AirAsia X, VietJet and Batik Air run monthly sales — Friday afternoons (AEST) for Jetstar's Friday Frenzy. Bali and Kuala Lumpur are the two cheapest entry points; everything in SEA is a $30–80 hop from KUL.",
  },
  "sea-sea": {
    label: "Within Southeast Asia",
    typ: [25, 90],
    advice: "AirAsia, VietJet, Scoot, Cebu Pacific and Lion Air keep intra-SEA fares tiny — but bag fees can double a $30 fare, so pack carry-on. For trips under ~500 km, buses and trains (book on 12Go) are often cheaper, comfier and station-to-station.",
  },
  "california-california": { label: "Within California", typ: [40, 120],
    advice: "Southwest, Alaska and United shuttle routes — or just drive." },
  "australia-australia": { label: "Within Australia", typ: [60, 180],
    advice: "Jetstar and Virgin sales; east-coast Greyhound hop-on-hop-off passes suit backpackers." },
};

/* Accommodation intel. Prices = USD/night typical. */
const STAYS = {
  "Bangkok": { country: "Thailand", dorm: [8, 15], private: [18, 30], hotel: [25, 45],
    areas: "Ari or Phaya Thai for local vibes on the BTS line; Old City (Banglamphu) for sights; skip the Khao San party blocks if you value sleep.",
    tip: "Bangkok hostels are some of the world's best-value — 8.5+ rated places with pools exist under $12." },
  "Chiang Mai": { country: "Thailand", dorm: [6, 12], private: [14, 25], hotel: [20, 38],
    areas: "Old City for walkability, Nimman for cafés and digital-nomad comforts.",
    tip: "Monthly guesthouse rates drop to $200–300 if you linger — ask in person." },
  "Phuket": { country: "Thailand", dorm: [8, 16], private: [20, 35], hotel: [28, 55],
    areas: "Phuket Old Town for charm and cheap eats; Kata/Karon quieter than Patong.",
    tip: "Stay in Old Town and day-trip to beaches by songthaew ($1) — beachfront prices double everything." },
  "Krabi": { country: "Thailand", dorm: [7, 14], private: [16, 28], hotel: [22, 45],
    areas: "Ao Nang for beach access, Krabi Town for half the price.",
    tip: "Railay's cheap-ish bungalows book out — reserve those 2+ weeks ahead." },
  "Hanoi": { country: "Vietnam", dorm: [5, 10], private: [14, 25], hotel: [20, 35],
    areas: "Old Quarter for the classic chaos, Tay Ho (West Lake) for calm.",
    tip: "Hostel 'free beer hour' places are party spots — check reviews for 'quiet' if that's not your scene." },
  "Ho Chi Minh City": { country: "Vietnam", dorm: [6, 11], private: [15, 26], hotel: [22, 40],
    areas: "District 1 (around Bui Vien is loud; go 3–4 blocks out), District 3 for local flavour.",
    tip: "$20 gets a genuinely nice private room here — Vietnam is where hotel upgrades cost least." },
  "Da Nang": { country: "Vietnam", dorm: [5, 10], private: [13, 24], hotel: [18, 35],
    areas: "My Khe beach side for sea air; An Thuong for the traveller enclave.",
    tip: "Consider staying in Hoi An instead (30 min) — homestays there are $15–25 and gorgeous." },
  "Siem Reap": { country: "Cambodia", dorm: [4, 9], private: [12, 22], hotel: [18, 35],
    areas: "Wat Bo Road area — close to the centre, quieter than Pub Street.",
    tip: "Hostels with pools under $8 are normal here. Get one — Angkor days are hot." },
  "Phnom Penh": { country: "Cambodia", dorm: [5, 10], private: [13, 24], hotel: [20, 38],
    areas: "BKK1 for comfort, Riverside for location.",
    tip: "Standards vary more than elsewhere — filter 8.0+ with 200+ reviews." },
  "Luang Prabang": { country: "Laos", dorm: [5, 10], private: [14, 25], hotel: [20, 40],
    areas: "Old Town peninsula — everything is walkable.",
    tip: "Guesthouses run by families often beat hostels on both price and cleanliness here." },
  "Vientiane": { country: "Laos", dorm: [5, 10], private: [13, 24], hotel: [18, 35],
    areas: "Near Nam Phou fountain for the compact centre.",
    tip: "Most travellers only need a night or two — it's a transit stop, spend your Laos time in Luang Prabang / Vang Vieng." },
  "Kuala Lumpur": { country: "Malaysia", dorm: [7, 13], private: [18, 30], hotel: [25, 45],
    areas: "Chinatown (Petaling Street) for hostels and food; Bukit Bintang for city buzz.",
    tip: "KL has luxury-grade capsule hostels at $12–15 — great for a comfy reset between flights." },
  "Penang": { country: "Malaysia", dorm: [6, 12], private: [15, 28], hotel: [22, 40],
    areas: "George Town heritage core — street art, hawker food, everything walkable.",
    tip: "Heritage shophouse guesthouses are the move — character for hostel prices." },
  "Singapore": { country: "Singapore", dorm: [20, 35], private: [60, 100], hotel: [80, 140],
    areas: "Chinatown and Lavender for the (relatively) affordable beds.",
    tip: "The budget-killer of SEA. Capsule pods keep it sane; 2–3 nights is plenty." },
  "Bali (Canggu)": { country: "Indonesia", dorm: [7, 14], private: [18, 35], hotel: [25, 50],
    areas: "Canggu for surf/social, Ubud for jungle calm, Uluwatu for cliffs and waves.",
    tip: "Guesthouses ('homestays') at $15–20 with breakfast often beat hostels. Monthly villa-room deals abound." },
  "Ubud": { country: "Indonesia", dorm: [6, 12], private: [15, 30], hotel: [22, 45],
    areas: "Just off Monkey Forest Road, or Penestanan for rice-field quiet.",
    tip: "Family compounds rent beautiful rooms with breakfast for $15 — book 1 night online, extend in person for less." },
  "Jakarta": { country: "Indonesia", dorm: [6, 12], private: [15, 28], hotel: [22, 40],
    areas: "Around Cikini/Menteng — most travellers just transit here.",
    tip: "Honestly? Fly into Bali or Yogyakarta instead unless you have business here." },
  "Manila": { country: "Philippines", dorm: [7, 13], private: [18, 32], hotel: [25, 45],
    areas: "Makati (Poblacion) — safe, walkable, great food scene.",
    tip: "Most backpackers transit fast to the islands — Poblacion is the one neighbourhood worth a night." },
  "Cebu": { country: "Philippines", dorm: [6, 12], private: [16, 30], hotel: [22, 42],
    areas: "Cebu City for transit; Moalboal (3h south) is the real draw.",
    tip: "Island-hopping beds (Moalboal, Siquijor, Bohol) are $8–15 — book only 1–2 days ahead, stay flexible." },
  "Sydney": { country: "Australia", dorm: [25, 45], private: [70, 110], hotel: [90, 150],
    areas: "Newtown for character, Coogee/Bondi for beach hostels, CBD YHA for location.",
    tip: "Weekly hostel rates cut 15–25%. If working-holidaying, many hostels trade beds for a few hours' work." },
  "Melbourne": { country: "Australia", dorm: [22, 40], private: [65, 100], hotel: [85, 140],
    areas: "Fitzroy/Collingwood for the cool stuff, CBD for transit ease.",
    tip: "Melbourne hostels are slightly cheaper than Sydney's and the free city tram zone saves real money." },
  "Brisbane": { country: "Australia", dorm: [20, 38], private: [60, 95], hotel: [80, 130],
    areas: "South Bank / West End.",
    tip: "Cheaper than Sydney/Melbourne — a good place to sort logistics before heading up the coast." },
  "Cairns": { country: "Australia", dorm: [20, 36], private: [55, 90], hotel: [75, 125],
    areas: "City centre near the Esplanade lagoon.",
    tip: "Book reef trips through your hostel — the discounts are genuine here." },
  "Gold Coast": { country: "Australia", dorm: [22, 40], private: [60, 100], hotel: [85, 140],
    areas: "Surfers Paradise for the action, Burleigh Heads for the better beach vibe.",
    tip: "Hostels here compete hard — look for free surfboard hire." },
  "Perth": { country: "Australia", dorm: [22, 38], private: [60, 95], hotel: [80, 130],
    areas: "Northbridge — hostels, food, nightlife in one walkable pocket.",
    tip: "Your last cheap-flight gateway to Asia — many backpackers end the Australia leg here on purpose." },
  "Mexico City": { country: "Mexico", dorm: [12, 20], private: [30, 50], hotel: [40, 70],
    areas: "Roma Norte and Condesa — leafy, walkable, café-dense and well-connected.",
    tip: "CDMX hostels are stylish and social; weekday prices drop noticeably vs weekends." },
  "Oaxaca": { country: "Mexico", dorm: [10, 18], private: [25, 45], hotel: [35, 60],
    areas: "Centro Histórico, anywhere walkable to the Zócalo.",
    tip: "Book ahead for Día de los Muertos (late Oct) — the city sells out months out." },
  "Antigua": { country: "Guatemala", dorm: [8, 15], private: [20, 35], hotel: [30, 55],
    areas: "Anywhere in the small colonial core — it's all walkable.",
    tip: "Volcano-hike operators bundle with hostels; compare the package price to booking separately." },
  "Medellín": { country: "Colombia", dorm: [8, 15], private: [22, 38], hotel: [30, 55],
    areas: "Laureles for local life (and better value); El Poblado for the traveller scene.",
    tip: "Colombia's hostel quality is world-class — 9.0+ rated places with pools under $12 exist." },
  "Cusco": { country: "Peru", dorm: [7, 14], private: [20, 35], hotel: [28, 50],
    areas: "San Blas for charm (uphill!), around Plaza de Armas for convenience.",
    tip: "Arrive 2 days before any trek to acclimatise — book a cheap bed for those, not a tour package." },
  "La Paz": { country: "Bolivia", dorm: [6, 12], private: [16, 28], hotel: [22, 40],
    areas: "Around Sagárnaga/Witches' Market for the backpacker core.",
    tip: "Bolivia is South America's cheapest country — a private room here costs what a dorm does in Chile." },
  "Buenos Aires": { country: "Argentina", dorm: [10, 18], private: [25, 45], hotel: [35, 65],
    areas: "San Telmo for character, Palermo for nightlife and parks.",
    tip: "Prices swing with the peso — pay in pesos at the informal rate where legal (Western Union pickup)." },
  "Lisbon": { country: "Portugal", dorm: [18, 30], private: [45, 75], hotel: [60, 100],
    areas: "Alfama for atmosphere, Arroios/Anjos for value a metro stop away.",
    tip: "Lisbon dorms beat most of Western Europe on price and quality — but book summer weeks ahead." },
  "Barcelona": { country: "Spain", dorm: [22, 38], private: [55, 90], hotel: [75, 120],
    areas: "Gràcia for neighbourhood feel; avoid La Rambla-adjacent party hostels for sleep.",
    tip: "City tourist tax adds €4–6/night — factor it in when comparing to nearby cities." },
  "Prague": { country: "Czechia", dorm: [14, 24], private: [40, 65], hotel: [55, 90],
    areas: "Žižkov or Vinohrady — 15 minutes from Old Town, half the price.",
    tip: "Central Europe sweet spot: Western polish, Eastern prices. Shoulder season (Apr–May, Sep–Oct) is ideal." },
  "Budapest": { country: "Hungary", dorm: [12, 22], private: [35, 60], hotel: [50, 85],
    areas: "District VII (Jewish Quarter) for the action, District IX for quiet value.",
    tip: "Thermal baths are the budget luxury — Rudas or Széchenyi is $20 well spent." },
  "Tirana": { country: "Albania", dorm: [10, 16], private: [25, 40], hotel: [35, 60],
    areas: "Blloku — the whole compact centre works.",
    tip: "Albania is Europe's best-value coastline: the Riviera (Himarë, Dhërmi) has $12 dorms steps from the beach." },
  "Istanbul": { country: "Türkiye", dorm: [10, 18], private: [30, 55], hotel: [40, 70],
    areas: "Kadıköy (Asian side) for local vibes and value; Sultanahmet only if it's your first visit.",
    tip: "Cross-continental ferries cost pennies — stay on the cheaper Asian side and commute by boat." },
  "Delhi": { country: "India", dorm: [5, 10], private: [15, 28], hotel: [22, 40],
    areas: "Paharganj for the classic budget scene, Hauz Khas for a gentler landing.",
    tip: "India rewards the 8.5+ rating filter more than anywhere — quality variance is extreme." },
  "Goa": { country: "India", dorm: [6, 12], private: [15, 30], hotel: [22, 45],
    areas: "Anjuna/Vagator in the north for the scene, Palolem in the south for calm.",
    tip: "November and February are the sweet spots — peak season (Dec–Jan) doubles prices." },
  "Kathmandu": { country: "Nepal", dorm: [4, 9], private: [12, 22], hotel: [18, 35],
    areas: "Thamel — the trekker's basecamp, everything you need in five blocks.",
    tip: "Teahouse beds on the trekking routes are $3–8/night; your Kathmandu hostel will store your spare bag free." },
  "Colombo": { country: "Sri Lanka", dorm: [8, 14], private: [20, 35], hotel: [28, 50],
    areas: "One night near Fort station, then move on — Sri Lanka's magic is Ella, Mirissa, Arugam Bay.",
    tip: "Guesthouses beat hostels across Sri Lanka: $15–25 gets a family-run room with breakfast." },
  "Tokyo": { country: "Japan", dorm: [18, 30], private: [45, 75], hotel: [60, 100],
    areas: "Asakusa for budget beds near sights, Shinjuku/Shibuya if nightlife matters more than price.",
    tip: "Capsule hotels ($25–40) are the experience <em>and</em> the budget move. Business hotels (APA, Toyoko Inn) undercut Airbnb." },
  "Seoul": { country: "South Korea", dorm: [12, 22], private: [35, 60], hotel: [45, 80],
    areas: "Hongdae for the young scene, Insadong for central calm.",
    tip: "Jjimjilbang (bathhouse) overnights are the famous $10–15 bed hack — one night is a rite of passage." },
  "Taipei": { country: "Taiwan", dorm: [12, 20], private: [35, 55], hotel: [45, 75],
    areas: "Ximending for the buzz, near any MRT station works — the metro is superb.",
    tip: "Night-market eating keeps food under $10/day, which offsets the mid-range bed prices." },
  "Marrakech": { country: "Morocco", dorm: [8, 15], private: [20, 40], hotel: [30, 55],
    areas: "A riad in the Medina is the experience — pick one within 10 minutes of Jemaa el-Fnaa.",
    tip: "Riad dorms and cheap private rooms often include rooftop breakfast — filter 8.5+ and it's hard to go wrong." },
  "Cape Town": { country: "South Africa", dorm: [12, 20], private: [35, 60], hotel: [45, 80],
    areas: "Gardens/Tamboerskloof for safety and cafés; Observatory for the student-y budget scene.",
    tip: "The Baz Bus hop-on-hop-off connects hostels along the Garden Route — cheaper than car hire solo." },
  "Auckland": { country: "New Zealand", dorm: [20, 35], private: [55, 90], hotel: [75, 120],
    areas: "City centre near Queen Street, or Ponsonby if you'll linger.",
    tip: "NZ hostels (YHA/Haka) are spotless. Most backpackers grab a cheap campervan relocation deal out of Auckland." },
};

/* Route strategies. Legs reference typical low fares; `daily` is the blended
   on-the-ground cost (bed + food + local transport + fun) in USD/day for the
   countries the route spends time in. Long-haul legs priced from the US west
   coast. */
const ROUTE_STRATEGIES = [
  {
    id: "reverse-loop",
    name: "The Reverse Loop",
    emoji: "🔄",
    region: "apac",
    regionLabel: "Australia + Southeast Asia",
    tagline: "Usually the cheapest way to do Australia + SEA — fly into Asia first, save Australia for last.",
    daily: { shoestring: 49, flashpacker: 74 },
    legs: [
      { from: "California", to: "Bangkok", mode: "flight", est: 420, note: "EVA/China Airlines/Korean sale fare, or ZipAir via Tokyo. Cheapest transpacific corridor." },
      { from: "Bangkok", to: "Chiang Mai & N. Thailand", mode: "ground", est: 30, note: "Sleeper train up, slow-boat or bus into Laos if you like." },
      { from: "Chiang Mai", to: "Hanoi", mode: "flight", est: 70, note: "Or overland through Laos (Luang Prabang) — slower, unforgettable." },
      { from: "Hanoi", to: "Ho Chi Minh City", mode: "ground", est: 45, note: "3–4 weeks down the coast: Ha Long, Hoi An, Da Lat. Sleeper trains/buses." },
      { from: "Ho Chi Minh City", to: "Bali", mode: "flight", est: 90, note: "VietJet nonstop, or via KUL for less." },
      { from: "Bali", to: "Sydney / Melbourne", mode: "flight", est: 170, note: "Jetstar sale fare. The cheap way into Australia." },
      { from: "Australia east coast", to: "", mode: "ground", est: 150, note: "Greyhound pass or a shared campervan relocation deal." },
      { from: "Sydney", to: "California", mode: "flight", est: 500, note: "Jetstar/Fiji Airways home. Book once you know your dates." },
    ],
    why: "You hit the expensive country (Australia) last, when you know exactly what's left in the kitty. Transpacific fares into Bangkok run $100–200 under Sydney fares, and your Australia entry becomes a ~$170 Bali hop instead of a $600 ocean crossing.",
  },
  {
    id: "classic-southbound",
    name: "The Classic Southbound",
    emoji: "🇦🇺",
    region: "apac",
    regionLabel: "Australia + Southeast Asia",
    tagline: "Australia first while your budget is fresh, then get cheap in Asia.",
    daily: { shoestring: 51, flashpacker: 77 },
    legs: [
      { from: "California", to: "Sydney", mode: "flight", est: 450, note: "Jetstar/Fiji Airways sale fare. April–May and Aug–Sep are cheapest." },
      { from: "Sydney", to: "Cairns (east coast)", mode: "ground", est: 180, note: "The classic backpacker run: Byron, Gold Coast, Noosa, Whitsundays." },
      { from: "Cairns/Brisbane", to: "Bali", mode: "flight", est: 180, note: "Or reposition to Darwin — DRW–Bali from $99." },
      { from: "Bali", to: "Kuala Lumpur", mode: "flight", est: 50, note: "AirAsia. KUL unlocks cheap fares to everywhere in SEA." },
      { from: "Kuala Lumpur", to: "Bangkok", mode: "flight", est: 40, note: "Or train up through Penang — one of Asia's great rail rides." },
      { from: "Thailand", to: "Vietnam (overland loop)", mode: "ground", est: 120, note: "Thailand → Cambodia (Angkor) → Vietnam by bus; visas on the way." },
      { from: "Ho Chi Minh City", to: "California", mode: "flight", est: 550, note: "One-way home; EVA/Korean via their hubs price best." },
    ],
    why: "Do the physically big, expensive country while you're fresh and funded, then let ultra-cheap Asia stretch the tail of your trip. Every flight after Australia costs less than a night out in Sydney.",
  },
  {
    id: "perth-backdoor",
    name: "The Perth Back Door",
    emoji: "🚪",
    region: "apac",
    regionLabel: "Australia + Southeast Asia",
    tagline: "Use Australia's west coast as the world's cheapest exit to Asia.",
    daily: { shoestring: 51, flashpacker: 77 },
    legs: [
      { from: "California", to: "Sydney", mode: "flight", est: 450, note: "Sale fare in; do the east coast first." },
      { from: "East coast", to: "Melbourne", mode: "ground", est: 100, note: "Buses/rideshares down the coast." },
      { from: "Melbourne", to: "Perth", mode: "flight", est: 120, note: "Jetstar/Virgin domestic sale. Margaret River side-trip if time allows." },
      { from: "Perth", to: "Bali", mode: "flight", est: 90, note: "The famous cheap hop — under AUD 99 in sales, 3.5 hours." },
      { from: "Bali", to: "Kuala Lumpur", mode: "flight", est: 50, note: "AirAsia into the hub." },
      { from: "Kuala Lumpur", to: "Bangkok + mainland loop", mode: "flight", est: 40, note: "Thailand → Laos → Vietnam overland from here." },
      { from: "Bangkok", to: "California", mode: "flight", est: 480, note: "Fly home from the region's best-connected hub." },
    ],
    why: "Perth–Bali is Australia's cheapest international flight, which turns the expensive 'Australia → Asia' leg into pocket change. You also see the west coast most backpackers skip.",
  },
  {
    id: "gringo-trail",
    name: "The Gringo Trail",
    emoji: "🌎",
    region: "latam",
    regionLabel: "Latin America",
    tagline: "Mexico to Patagonia's doorstep — the classic Latin America line, no ocean crossing needed.",
    daily: { shoestring: 40, flashpacker: 65 },
    legs: [
      { from: "California", to: "Mexico City", mode: "flight", est: 150, note: "Volaris/VivaAerobus — or walk the CBX bridge at Tijuana and fly domestic-Mexico prices." },
      { from: "Mexico City", to: "Oaxaca & Chiapas", mode: "ground", est: 60, note: "ADO buses — comfortable, safe, everywhere." },
      { from: "Chiapas", to: "Central America (overland)", mode: "ground", est: 130, note: "Guatemala (Antigua, Atitlán) → El Salvador → Nicaragua → Costa Rica → Panama by chicken bus and shuttle." },
      { from: "Panama City", to: "Medellín", mode: "flight", est: 120, note: "Wingo/Avianca. No road through the Darién Gap — everyone flies (or sails via San Blas, ~$500)." },
      { from: "Colombia", to: "Lima / Cusco", mode: "flight", est: 110, note: "JetSmart/LATAM sales; or overland through Ecuador if you have the weeks." },
      { from: "Cusco", to: "La Paz, Bolivia", mode: "ground", est: 40, note: "Bus via Lake Titicaca (Copacabana). Bolivia is the cheapest country on the continent." },
      { from: "La Paz", to: "Buenos Aires", mode: "flight", est: 130, note: "Or the epic 3-day bus run via Salta if the budget is tighter than the schedule." },
      { from: "Buenos Aires", to: "California", mode: "flight", est: 480, note: "One-way home; watch Aeroméxico/Copa connections for the best fares." },
    ],
    why: "Short cheap flights instead of ocean crossings: your longest single fare is the trip home. Daily costs sit between SEA and Australia, buses replace half the flights, and the currency math (Argentina especially) often works in your favour.",
  },
  {
    id: "subcontinent",
    name: "The Subcontinent Special",
    emoji: "🛕",
    region: "southasia",
    regionLabel: "South Asia",
    tagline: "India, Nepal and Sri Lanka — the lowest daily costs on Earth per unit of wonder.",
    daily: { shoestring: 30, flashpacker: 50 },
    legs: [
      { from: "California", to: "Delhi", mode: "flight", est: 500, note: "Sale fares via East Asian or Gulf hubs; October–March is both the best season and the fare sweet spot." },
      { from: "Delhi", to: "Rajasthan loop", mode: "ground", est: 50, note: "Jaipur, Jodhpur, Udaipur by train — book sleeper class a few days ahead." },
      { from: "Rajasthan", to: "Agra & Varanasi", mode: "ground", est: 30, note: "The Taj at dawn, then the ghats. Trains again." },
      { from: "Varanasi", to: "Kathmandu", mode: "flight", est: 60, note: "Buddha Air/IndiGo via Delhi, or the border bus if you enjoy an adventure." },
      { from: "Nepal", to: "trekking (EBC/Annapurna)", mode: "ground", est: 100, note: "Permits + teahouses. The best-value world-class experience in travel." },
      { from: "Kathmandu", to: "Colombo", mode: "flight", est: 180, note: "Via Delhi or Chennai on IndiGo/Air India Express." },
      { from: "Sri Lanka loop", to: "", mode: "ground", est: 40, note: "Ella's trains, Mirissa's whales, Arugam Bay's surf — buses and the famous hill railway." },
      { from: "Colombo", to: "California", mode: "flight", est: 550, note: "One-way home via a Gulf or SEA hub." },
    ],
    why: "At $30/day shoestring, every week here costs what 2–3 days costs in Australia. The flights bracket the trip; in between, trains and buses cost single-digit dollars and <em>are</em> the experience.",
  },
  {
    id: "euro-shoestring",
    name: "The Euro Shoestring",
    emoji: "🏰",
    region: "europe",
    regionLabel: "Europe",
    tagline: "Europe without the Western-Europe bill — head south and east, fast.",
    daily: { shoestring: 55, flashpacker: 85 },
    legs: [
      { from: "California", to: "Lisbon", mode: "flight", est: 380, note: "TAP sales, or a Norse/French Bee cheap seat into Paris/London + a $30 Ryanair hop." },
      { from: "Portugal & Spain", to: "", mode: "ground", est: 90, note: "Lisbon → Lagos → Seville → Madrid/Barcelona by FlixBus and ALSA." },
      { from: "Barcelona", to: "Tirana", mode: "flight", est: 60, note: "Ryanair/Wizz. Albania is Western-Europe beauty at Southeast-Asia-adjacent prices." },
      { from: "Balkans (overland)", to: "", mode: "ground", est: 120, note: "Albanian Riviera → Montenegro → Bosnia → Serbia by bus. The best-value corner of Europe." },
      { from: "Belgrade", to: "Budapest & Prague", mode: "ground", est: 60, note: "Trains/FlixBus north through Central Europe's greatest hits." },
      { from: "Prague", to: "California", mode: "flight", est: 430, note: "One-way home; position to London/Paris on a $25 budget hop if it's cheaper." },
    ],
    why: "The route spends 80% of its nights in Portugal, the Balkans and Central Europe, where beds are half of the Paris/Amsterdam price — while the budget-airline network keeps every reposition under $60.",
  },
];

/* Flexible-cancellation playbook — backpacking is spontaneous; book like it. */
const FLEX_GUIDE = {
  intro: "Backpacking plans have a half-life of about two weeks. The fix isn't planning harder — it's booking things you're allowed to change.",
  flights: {
    title: "✈️ Flights that forgive you",
    points: [
      "<strong>Book one-way legs as you go.</strong> The single best flexibility hack: skip round-trips and multi-city tickets, book each hop 1–3 weeks out. You pay a little more per leg and never eat a cancelled itinerary. Intra-SEA, intra-Europe and intra-LatAm fares barely rise close-in.",
      "<strong>Use the free 24-hour window.</strong> Any ticket touching the US (and bookings on most major airline sites) can be cancelled free within 24 hours of purchase — US DOT rule. Book the moment you see a deal, confirm your plan overnight, cancel penalty-free if it falls apart.",
      "<strong>Buy the airline's flex bundle only on long-hauls.</strong> On a $500 transpacific fare, the ~$40–80 'flex/changeable' upsell is worth it; on a $35 AirAsia hop it never is — treat cheap tickets as disposable.",
      "<strong>Book direct with the airline, not an OTA.</strong> When plans change, airlines can rebook you in one chat; third-party bookings (Kiwi, eDreams, Trip.com) add a middleman fee and days of delay. Use the OTAs to <em>find</em> the fare, then buy it on the airline's own site.",
      "<strong>Know the credit rules.</strong> Most low-cost carriers won't refund but will issue flight credit for a small fee if <em>you</em> change first (Jetstar, AirAsia). If the <em>airline</em> changes the schedule — common on budget carriers — you're usually owed a full refund: take it.",
    ],
  },
  stays: {
    title: "🛏️ Beds you can walk away from",
    points: [
      "<strong>Filter, don't hope.</strong> Booking.com and Agoda both have a 'free cancellation' filter — the Stays tab's checkbox applies it for you. The flexible rate usually costs 5–15% more; think of it as insurance that costs less than one wasted night.",
      "<strong>Hostelworld's deposit model is flex by default.</strong> You pay ~10–15% deposit online and the rest at the desk; most listings offer free cancellation up to 24–48h before. Pick 'Free cancellation' rates over 'Non-refundable' — the difference is usually under $1 on a dorm.",
      "<strong>On Airbnb, check the policy line first.</strong> Filter or scan for 'Flexible' (full refund until 24h before) or 'Moderate' (until 5 days before). 'Strict' listings are for people with return tickets.",
      "<strong>Book 1–2 nights, extend in person.</strong> The backpacker classic: reserve just your arrival nights online, then extend at the desk (often cheaper) or walk to the better hostel you found around the corner. You're never locked into a place that looked better in photos.",
      "<strong>Long stays: pay weekly, not monthly upfront.</strong> Monthly discounts are tempting, but a weekly rolling rate keeps you free to chase the weather, the crew you met, or the festival two islands over — which is the whole point.",
    ],
  },
};

const DEAL_HACKS = [
  { icon: "📅", title: "Know the sale calendar",
    body: "Jetstar Friday Frenzy: Friday ~4pm AEST weekly. AirAsia BIG Sale: ~4× a year (Feb/Mar, May/Jun, Aug/Sep, Nov). Scoot flash sales: most Tuesdays. Cebu Pacific Piso sales: around Philippine holidays. VietJet: sales nearly monthly. Set calendar reminders — sale fares are 40–70% off." },
  { icon: "🎒", title: "Carry-on only changes the math",
    body: "Budget-carrier bag fees ($25–45 per flight) can double a $40 fare across a multi-hop trip. A 35–40L pack under 7kg flies free on AirAsia, VietJet, Scoot and Jetstar. Ten flights ≈ $350 saved." },
  { icon: "🔔", title: "Track, don't stalk",
    body: "Set Google Flights price tracking on your long-haul legs 3–5 months out and book when a genuine dip shows. For CA↔Australia, under $500 one-way is 'book it now' territory; under $420 is exceptional." },
  { icon: "🚌", title: "Under 500 km, go by land",
    body: "Buses and trains in SEA are comfortable, cheap and station-to-station: Bangkok–Chiang Mai sleeper $25, Saigon–Phnom Penh bus $20, KL–Singapore bus $12. Book on 12Go. You save a night's accommodation on sleepers, too." },
  { icon: "🏨", title: "The clean-bed formula",
    body: "Filter stays to rating ≥ 8.3 with 150+ reviews, then read only the recent negative reviews — that's where cleanliness truth lives. On Hostelworld sort by rating, not price: in SEA the difference between a 7.8 and a 9.2 hostel is often $2." },
  { icon: "↩️", title: "Book flexible, especially early legs",
    body: "Choose free-cancellation stays (Booking/Agoda make this a filter) for your first nights in each country and lock in the rest once you're on the ground. Plans made from home rarely survive week two." },
  { icon: "💳", title: "Kill the hidden 3–7%",
    body: "Use a no-foreign-fee card (Wise/Revolut/Charles Schwab), always pay in local currency (decline 'dynamic currency conversion'), and skip airport exchange counters. In Vietnam and Indonesia, withdraw large amounts less often — ATM fees are per-transaction." },
  { icon: "🗓️", title: "Fly on the cheap days",
    body: "Tuesday/Wednesday departures price lowest on long-haul; intra-SEA barely varies. Avoid arriving anywhere during Lunar New Year, Songkran (mid-April) or Christmas–NYE unless you've booked well ahead." },
  { icon: "🛂", title: "Budget the visas",
    body: "Thailand: 60 days free (US passport). Indonesia: $35 visa on arrival. Vietnam: e-visa $25 (apply 1–2 weeks early). Cambodia: $30 e-visa. Laos: ~$40 on arrival. Australia: free ETA (or the Work & Holiday visa if you want to earn AUD along the way)." },
  { icon: "🧭", title: "Season your route",
    body: "SEA mainland is driest Nov–Apr; Bali is best Apr–Oct; Australia's east coast shines Sep–Nov and Mar–May. The Reverse Loop timed to leave California in October threads all three." },
];

/* =========================================================================
   Custom route builder — country knowledge base.
   gateway: main budget-flight entry airport. lat/lon: that airport.
   zone: overland-connected cluster (same zone + <1,600 km ⇒ bus/train leg).
   market: regional airfare market, used to scale flight estimates.
   daily: on-the-ground USD/day [shoestring, flashpacker].
   days: suggested days for a satisfying visit (scaled to fit the trip).
   ========================================================================= */

const COUNTRIES = {
  // Southeast Asia
  "Thailand":     { gateway: "Bangkok (BKK)",        lat: 13.69,  lon: 100.75,  zone: "seaMain",  market: "sea",       daily: [35, 55],  days: 18 },
  "Vietnam":      { gateway: "Ho Chi Minh City (SGN)", lat: 10.82, lon: 106.65, zone: "seaMain",  market: "sea",       daily: [30, 50],  days: 16 },
  "Cambodia":     { gateway: "Phnom Penh (PNH)",     lat: 11.55,  lon: 104.84,  zone: "seaMain",  market: "sea",       daily: [30, 50],  days: 8 },
  "Laos":         { gateway: "Vientiane (VTE)",      lat: 17.99,  lon: 102.56,  zone: "seaMain",  market: "sea",       daily: [28, 48],  days: 8 },
  "Malaysia":     { gateway: "Kuala Lumpur (KUL)",   lat: 2.75,   lon: 101.71,  zone: "seaMain",  market: "sea",       daily: [35, 55],  days: 8 },
  "Singapore":    { gateway: "Singapore (SIN)",      lat: 1.36,   lon: 103.99,  zone: "seaMain",  market: "sea",       daily: [65, 95],  days: 3 },
  "Indonesia":    { gateway: "Bali (DPS)",           lat: -8.75,  lon: 115.17,  zone: "indonesia", market: "sea",      daily: [32, 55],  days: 14 },
  "Philippines":  { gateway: "Manila (MNL)",         lat: 14.51,  lon: 121.02,  zone: "philippines", market: "sea",    daily: [35, 55],  days: 12 },
  // East Asia
  "Japan":        { gateway: "Tokyo (HND)",          lat: 35.55,  lon: 139.78,  zone: "japan",    market: "eastasia",  daily: [70, 110], days: 12 },
  "South Korea":  { gateway: "Seoul (ICN)",          lat: 37.46,  lon: 126.44,  zone: "korea",    market: "eastasia",  daily: [55, 90],  days: 7 },
  "Taiwan":       { gateway: "Taipei (TPE)",         lat: 25.08,  lon: 121.23,  zone: "taiwan",   market: "eastasia",  daily: [50, 80],  days: 7 },
  "Hong Kong":    { gateway: "Hong Kong (HKG)",      lat: 22.31,  lon: 113.91,  zone: "eastasiaMain", market: "eastasia", daily: [60, 100], days: 3 },
  "China":        { gateway: "Shanghai (PVG)",       lat: 31.14,  lon: 121.81,  zone: "eastasiaMain", market: "eastasia", daily: [45, 75], days: 12 },
  // South Asia
  "India":        { gateway: "Delhi (DEL)",          lat: 28.57,  lon: 77.10,   zone: "southasia", market: "southasia", daily: [25, 45], days: 21 },
  "Nepal":        { gateway: "Kathmandu (KTM)",      lat: 27.70,  lon: 85.36,   zone: "southasia", market: "southasia", daily: [25, 45], days: 12 },
  "Sri Lanka":    { gateway: "Colombo (CMB)",        lat: 7.18,   lon: 79.88,   zone: "srilanka", market: "southasia", daily: [30, 50],  days: 10 },
  // Oceania
  "Australia":    { gateway: "Sydney (SYD)",         lat: -33.95, lon: 151.18,  zone: "australia", market: "oceania",  daily: [75, 110], days: 21 },
  "New Zealand":  { gateway: "Auckland (AKL)",       lat: -37.01, lon: 174.79,  zone: "nz",       market: "oceania",   daily: [70, 105], days: 14 },
  "Fiji":         { gateway: "Nadi (NAN)",           lat: -17.76, lon: 177.44,  zone: "fiji",     market: "oceania",   daily: [55, 90],  days: 5 },
  // Latin America
  "Mexico":       { gateway: "Mexico City (MEX)",    lat: 19.44,  lon: -99.07,  zone: "latamN",   market: "latam",     daily: [40, 65],  days: 14 },
  "Guatemala":    { gateway: "Guatemala City (GUA)", lat: 14.58,  lon: -90.53,  zone: "latamN",   market: "latam",     daily: [30, 50],  days: 8 },
  "Nicaragua":    { gateway: "Managua (MGA)",        lat: 12.14,  lon: -86.17,  zone: "latamN",   market: "latam",     daily: [30, 50],  days: 6 },
  "Costa Rica":   { gateway: "San José (SJO)",       lat: 9.99,   lon: -84.20,  zone: "latamN",   market: "latam",     daily: [50, 80],  days: 8 },
  "Panama":       { gateway: "Panama City (PTY)",    lat: 9.07,   lon: -79.38,  zone: "latamN",   market: "latam",     daily: [45, 70],  days: 5 },
  "Colombia":     { gateway: "Medellín (MDE)",       lat: 6.16,   lon: -75.42,  zone: "latamS",   market: "latam",     daily: [35, 55],  days: 12 },
  "Ecuador":      { gateway: "Quito (UIO)",          lat: -0.13,  lon: -78.36,  zone: "latamS",   market: "latam",     daily: [30, 50],  days: 8 },
  "Peru":         { gateway: "Lima (LIM)",           lat: -12.02, lon: -77.11,  zone: "latamS",   market: "latam",     daily: [32, 52],  days: 12 },
  "Bolivia":      { gateway: "La Paz (LPB)",         lat: -16.51, lon: -68.19,  zone: "latamS",   market: "latam",     daily: [25, 45],  days: 8 },
  "Chile":        { gateway: "Santiago (SCL)",       lat: -33.39, lon: -70.79,  zone: "latamS",   market: "latam",     daily: [50, 80],  days: 10 },
  "Argentina":    { gateway: "Buenos Aires (EZE)",   lat: -34.82, lon: -58.54,  zone: "latamS",   market: "latam",     daily: [40, 65],  days: 12 },
  "Brazil":       { gateway: "Rio de Janeiro (GIG)", lat: -22.81, lon: -43.25,  zone: "latamS",   market: "latam",     daily: [40, 65],  days: 14 },
  // Europe
  "Portugal":     { gateway: "Lisbon (LIS)",         lat: 38.77,  lon: -9.13,   zone: "europe",   market: "europe",    daily: [55, 85],  days: 8 },
  "Spain":        { gateway: "Madrid (MAD)",         lat: 40.47,  lon: -3.56,   zone: "europe",   market: "europe",    daily: [60, 95],  days: 10 },
  "France":       { gateway: "Paris (CDG)",          lat: 49.01,  lon: 2.55,    zone: "europe",   market: "europe",    daily: [75, 115], days: 7 },
  "United Kingdom": { gateway: "London (LHR)",       lat: 51.47,  lon: -0.45,   zone: "europe",   market: "europe",    daily: [75, 115], days: 6 },
  "Netherlands":  { gateway: "Amsterdam (AMS)",      lat: 52.31,  lon: 4.76,    zone: "europe",   market: "europe",    daily: [75, 120], days: 4 },
  "Germany":      { gateway: "Berlin (BER)",         lat: 52.36,  lon: 13.50,   zone: "europe",   market: "europe",    daily: [65, 100], days: 7 },
  "Czechia":      { gateway: "Prague (PRG)",         lat: 50.10,  lon: 14.26,   zone: "europe",   market: "europe",    daily: [50, 80],  days: 5 },
  "Poland":       { gateway: "Kraków (KRK)",         lat: 50.08,  lon: 19.78,   zone: "europe",   market: "europe",    daily: [45, 70],  days: 6 },
  "Hungary":      { gateway: "Budapest (BUD)",       lat: 47.44,  lon: 19.26,   zone: "europe",   market: "europe",    daily: [45, 75],  days: 5 },
  "Croatia":      { gateway: "Split (SPU)",          lat: 43.54,  lon: 16.30,   zone: "europe",   market: "europe",    daily: [50, 85],  days: 7 },
  "Albania":      { gateway: "Tirana (TIA)",         lat: 41.41,  lon: 19.72,   zone: "europe",   market: "europe",    daily: [40, 65],  days: 6 },
  "Greece":       { gateway: "Athens (ATH)",         lat: 37.94,  lon: 23.94,   zone: "europe",   market: "europe",    daily: [50, 85],  days: 8 },
  "Italy":        { gateway: "Rome (FCO)",           lat: 41.80,  lon: 12.24,   zone: "europe",   market: "europe",    daily: [65, 100], days: 9 },
  "Türkiye":      { gateway: "Istanbul (IST)",       lat: 41.26,  lon: 28.74,   zone: "europe",   market: "europe",    daily: [40, 65],  days: 8 },
  // Middle East & Africa
  "Morocco":      { gateway: "Marrakech (RAK)",      lat: 31.61,  lon: -8.03,   zone: "morocco",  market: "mea",       daily: [35, 60],  days: 8 },
  "Egypt":        { gateway: "Cairo (CAI)",          lat: 30.12,  lon: 31.41,   zone: "mideast",  market: "mea",       daily: [30, 55],  days: 8 },
  "Jordan":       { gateway: "Amman (AMM)",          lat: 31.72,  lon: 35.99,   zone: "mideast",  market: "mea",       daily: [45, 75],  days: 5 },
  "UAE":          { gateway: "Dubai (DXB)",          lat: 25.25,  lon: 55.36,   zone: "mideast",  market: "mea",       daily: [65, 105], days: 3 },
  "Kenya":        { gateway: "Nairobi (NBO)",        lat: -1.32,  lon: 36.93,   zone: "kenya",    market: "mea",       daily: [40, 70],  days: 8 },
  "South Africa": { gateway: "Cape Town (CPT)",      lat: -33.97, lon: 18.60,   zone: "southafrica", market: "mea",    daily: [40, 70],  days: 12 },
};

/* Home bases the trip starts and ends at. */
const ORIGINS = [
  { name: "Los Angeles, California", lat: 33.94, lon: -118.41, market: "na" },
  { name: "San Francisco, California", lat: 37.62, lon: -122.38, market: "na" },
  { name: "New York, USA", lat: 40.64, lon: -73.78, market: "na" },
  { name: "Vancouver, Canada", lat: 49.19, lon: -123.18, market: "na" },
  { name: "London, UK", lat: 51.47, lon: -0.45, market: "europe" },
  { name: "Sydney, Australia", lat: -33.95, lon: 151.18, market: "oceania" },
];
